### ISSUE TITLE
eror ig

### ISSUE THREAD

**Issue by muklisadi** [akbaryahya/MultiMining#2]
Problem: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiMining.GUI_royal.<StartBot>b__12_0(Object state)

**Comment by nengmaya** [comment]
Masih Error Nih Gan... 

Problem: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object. at MultiMining.GUI_royal.b__12_0(Object state)
--
