### ISSUE TITLE
Order Followers Ga Masuk .

### ISSUE THREAD

**Issue by Hawkes127** [akbaryahya/MultiMining#5]
![screenshot_210](https://cloud.githubusercontent.com/assets/28433148/25738942/ddfa2372-31a9-11e7-9ede-e0532b3b7e05.png)

Kenapa Ya Kalo Order Ke Akun Yg 1 Itu Sekarang Ngak Bisa Masuk Followers Nya , Tapi Kalau Like / Viewers Bisa Masuk :) . Tapi Kalo Ane Test Ke Akun Lain Masuk  . Padahal Itu Akun Ngak Di Private + Dulu Order Followers Nya Masih Masuk . Mulainya 3 Hari Yg Lalu Sampai Sekarang Udah Coba Ganti Username Tapi Akun Masih Sama Tetep Sama Aja

**Comment by akbaryahya** [comment]
dbnya dikit dari sana
