### ISSUE TITLE
Multimining eror

### ISSUE THREAD

**Issue by Umarcahya2008** [akbaryahya/MultiMining#6]
Mas multiminingnya kalau di pc saya eror itu karena apa apa karena pakai windows 7 ya???

**Comment by akbaryahya** [comment]
ss coba

**Comment by vconstantin** [comment]
cara dapetin voc gojek gmna kang?

**Comment by putrasinaga123** [comment]
![image](https://cloud.githubusercontent.com/assets/18395688/25965815/13a24b88-3657-11e7-8591-2e85783eed30.png)

**Comment by meliana5** [comment]
Bang rilis via hp dong miningnya

**Comment by triasahoy** [comment]
ane pakai RDP bagian bar , Regis login dsb 

gak bisa di klik , alhasil cuma guest
