### ISSUE TITLE
Ga bisa login -_-

### ISSUE THREAD

**Issue by iqbal402** [akbaryahya/MultiMining#7]
dipencet login cuma nge reset username sama password doang login mah kaga -_-
![image](https://cloud.githubusercontent.com/assets/20736831/26055795/a31d8046-399c-11e7-90c4-5ccccea3ded5.png)

**Comment by akbaryahya** [comment]
klik tamu aja dulu

**Comment by iqbal402** [comment]
![image](https://cloud.githubusercontent.com/assets/20736831/26056534/fc7f103e-399f-11e7-81f4-fd4c028a99ce.png)
jadi begini bro

**Comment by akbaryahya** [comment]
pastikan kamu punya internet buat konek app, saya tau di browser emang bisa internet yang pasti cari caranya gimana internet bisa konek ke app itu
